# Spring properties
spring:
  freemarker:
    enabled: false     # Ignore Eureka dashboard FreeMarker templates
 
# Map the error path to error template (for Thymeleaf)
error:
  path=/error
 
# Discovery Server Access
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/
 
# HTTP Server
server:
  port: 5555   # HTTP (Tomcat) port